name: Build

on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 12 * * 1,5'  # Run at 12:00 UTC on Monday and Friday
  workflow_dispatch:

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    needs: sonarqube
    strategy:
      matrix:
        proto-convert-version: ["0.4.2", "0.4.1", "0.4.0"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "djipy"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          tags: |
            djipy/proto-convert:${{ matrix.proto-convert-version }}
            ${{ matrix.proto-convert-version == '0.4.2' && 'djipy/proto-convert:latest' || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          build-args: |
            PROTO_CONVERT_VERSION=${{ matrix.proto-convert-version }}